export interface ColumnsProps {
    id: number;
    des_campo: string;
    visible: boolean;
    default: number | string;
    type: string;
    removeCaractersBlock: boolean;
    removeCaracters: boolean;
    autoPlu: boolean;
    sizeOfField: boolean;
    size: number;
    genPlu: boolean;
    indexCodBarras: number;
    tratarCodBarras: boolean;
}

const ncm: ColumnsProps[] = [
    {
        id: 1, // indice
        des_campo: 'COD_NCM', // descrição do campo no banco do solidus
        visible: false,
        default: 1, // valor padrão para o campo
        type: 'number', // tipo de dado do campo number string boolean
        removeCaractersBlock: false,
        removeCaracters: false, // informa se esse campo remove caracteres especiais
        autoPlu: false,
        sizeOfField: false, // indica se o campo deve ser trucando
        size: 50, // tamanho do campo
        genPlu: false, // gerar PLU automativamente
        indexCodBarras: 99999,
        tratarCodBarras: false,
    },
    {
        id: 2,
        des_campo: 'DES_NCM',
        visible: false,
        default: 'null',
        type: 'string',
        removeCaractersBlock: false,
        removeCaracters: false,
        autoPlu: false,
        sizeOfField: false,
        size: 50,
        genPlu: false,
        indexCodBarras: 99999,
        tratarCodBarras: false,
    },
    {
        id: 3,
        des_campo: 'NUM_NCM',
        visible: false,
        default: 'null',
        type: 'string',
        removeCaractersBlock: false,
        removeCaracters: false,
        autoPlu: false,
        sizeOfField: false,
        size: 50,
        genPlu: false,
        indexCodBarras: 99999,
        tratarCodBarras: false,
    },
    {
        id: 4,
        des_campo: 'TIPO_PIS_COFINS',
        visible: false,
        default: 0,
        type: 'number',
        removeCaractersBlock: false,
        removeCaracters: false,
        autoPlu: false,
        sizeOfField: false,
        size: 50,
        genPlu: false,
        indexCodBarras: 99999,
        tratarCodBarras: false,
    },
    {
        id: 5,
        des_campo: 'TIPO_NAO_PIS_COFINS',
        visible: false,
        default: 1,
        type: 'number',
        removeCaractersBlock: false,
        removeCaracters: false,
        autoPlu: false,
        sizeOfField: false,
        size: 50,
        genPlu: false,
        indexCodBarras: 99999,
        tratarCodBarras: false,
    },
    {
        id: 6,
        des_campo: 'COD_TAB_SPED',
        visible: false,
        default: 1,
        type: 'number',
        removeCaractersBlock: false,
        removeCaracters: false,
        autoPlu: false,
        sizeOfField: false,
        size: 50,
        genPlu: false,
        indexCodBarras: 99999,
        tratarCodBarras: false,
    },
    {
        id: 7,
        des_campo: 'DES_TAB_SPED',
        visible: false,
        default: 'null',
        type: 'string',
        removeCaractersBlock: false,
        removeCaracters: false,
        autoPlu: false,
        sizeOfField: false,
        size: 50,
        genPlu: false,
        indexCodBarras: 99999,
        tratarCodBarras: false,
    },
    {
        id: 8,
        des_campo: 'COD_CRED_PRES',
        visible: false,
        default: 1,
        type: 'number',
        removeCaractersBlock: false,
        removeCaracters: false,
        autoPlu: false,
        sizeOfField: false,
        size: 50,
        genPlu: false,
        indexCodBarras: 99999,
        tratarCodBarras: false,
    },
    {
        id: 9,
        des_campo: 'PER_ALIQ_IMP',
        visible: false,
        default: 1,
        type: 'number',
        removeCaractersBlock: false,
        removeCaracters: false,
        autoPlu: false,
        sizeOfField: false,
        size: 50,
        genPlu: false,
        indexCodBarras: 99999,
        tratarCodBarras: false,
    },
    {
        id: 10,
        des_campo: 'PER_ALIQ_NAC',
        visible: false,
        default: 1,
        type: 'number',
        removeCaractersBlock: false,
        removeCaracters: false,
        autoPlu: false,
        sizeOfField: false,
        size: 50,
        genPlu: false,
        indexCodBarras: 99999,
        tratarCodBarras: false,
    },
    {
        id: 11,
        des_campo: 'PER_TAXA_DEPREC',
        visible: false,
        default: 1,
        type: 'number',
        removeCaractersBlock: false,
        removeCaracters: false,
        autoPlu: false,
        sizeOfField: false,
        size: 50,
        genPlu: false,
        indexCodBarras: 99999,
        tratarCodBarras: false,
    },
    {
        id: 12,
        des_campo: 'FLG_EST_CRED_ICMS',
        visible: false,
        default: 1,
        type: 'boolean',
        removeCaractersBlock: false,
        removeCaracters: false,
        autoPlu: false,
        sizeOfField: false,
        size: 50,
        genPlu: false,
        indexCodBarras: 99999,
        tratarCodBarras: false,
    },
    {
        id: 13,
        des_campo: 'PER_ALIQ_EST',
        visible: false,
        default: 1,
        type: 'number',
        removeCaractersBlock: false,
        removeCaracters: false,
        autoPlu: false,
        sizeOfField: false,
        size: 50,
        genPlu: false,
        indexCodBarras: 99999,
        tratarCodBarras: false,
    },
    {
        id: 14,
        des_campo: 'PER_ALIQ_MUN',
        visible: false,
        default: 1,
        type: 'number',
        removeCaractersBlock: false,
        removeCaracters: false,
        autoPlu: false,
        sizeOfField: false,
        size: 50,
        genPlu: false,
        indexCodBarras: 99999,
        tratarCodBarras: false,
    },
    {
        id: 15,
        des_campo: 'CHAVE_IBPT',
        visible: false,
        default: 1,
        type: 'number',
        removeCaractersBlock: false,
        removeCaracters: false,
        autoPlu: false,
        sizeOfField: false,
        size: 50,
        genPlu: false,
        indexCodBarras: 99999,
        tratarCodBarras: false,
    },
    {
        id: 16,
        des_campo: 'FLG_INATIVO',
        visible: false,
        default: 1,
        type: 'boolean',
        removeCaractersBlock: false,
        removeCaracters: false,
        autoPlu: false,
        sizeOfField: false,
        size: 50,
        genPlu: false,
        indexCodBarras: 99999,
        tratarCodBarras: false,
    },
    {
        id: 17,
        des_campo: 'COD_CEST',
        visible: false,
        default: 1,
        type: 'number',
        removeCaractersBlock: false,
        removeCaracters: false,
        autoPlu: false,
        sizeOfField: false,
        size: 50,
        genPlu: false,
        indexCodBarras: 99999,
        tratarCodBarras: false,
    },
    {
        id: 18,
        des_campo: 'FLG_VEDA_CRED',
        visible: false,
        default: 1,
        type: 'boolean',
        removeCaractersBlock: false,
        removeCaracters: false,
        autoPlu: false,
        sizeOfField: false,
        size: 50,
        genPlu: false,
        indexCodBarras: 99999,
        tratarCodBarras: false,
    },
    {
        id: 19,
        des_campo: 'COD_CRED_OUTORG',
        visible: false,
        default: 1,
        type: 'number',
        removeCaractersBlock: false,
        removeCaracters: false,
        autoPlu: false,
        sizeOfField: false,
        size: 50,
        genPlu: false,
        indexCodBarras: 99999,
        tratarCodBarras: false,
    },
    {
        id: 20,
        des_campo: 'NUM_EXTIPI',
        visible: false,
        default: 1,
        type: 'number',
        removeCaractersBlock: false,
        removeCaracters: false,
        autoPlu: false,
        sizeOfField: false,
        size: 50,
        genPlu: false,
        indexCodBarras: 99999,
        tratarCodBarras: false,
    },
    {
        id: 21,
        des_campo: 'FLG_VEDA_CRED_LIM',
        visible: false,
        default: 1,
        type: 'boolean',
        removeCaractersBlock: false,
        removeCaracters: false,
        autoPlu: false,
        sizeOfField: false,
        size: 50,
        genPlu: false,
        indexCodBarras: 99999,
        tratarCodBarras: false,
    },
    {
        id: 22,
        des_campo: 'PER_VEDA_CRED_LIM',
        visible: false,
        default: 1,
        type: 'number',
        removeCaractersBlock: false,
        removeCaracters: false,
        autoPlu: false,
        sizeOfField: false,
        size: 50,
        genPlu: false,
        indexCodBarras: 99999,
        tratarCodBarras: false,
    },
    {
        id: 23,
        des_campo: 'FLG_TRIB_ENT_TRANSF',
        visible: false,
        default: 1,
        type: 'boolean',
        removeCaractersBlock: false,
        removeCaracters: false,
        autoPlu: false,
        sizeOfField: false,
        size: 50,
        genPlu: false,
        indexCodBarras: 99999,
        tratarCodBarras: false,
    },
    {
        id: 24,
        des_campo: 'COD_CONCAT',
        visible: false,
        default: 1,
        type: 'number',
        removeCaractersBlock: false,
        removeCaracters: false,
        autoPlu: false,
        sizeOfField: false,
        size: 50,
        genPlu: false,
        indexCodBarras: 99999,
        tratarCodBarras: false,
    },
    {
        id: 25,
        des_campo: 'COD_TRIBUTACAO',
        visible: false,
        default: 1,
        type: 'number',
        removeCaractersBlock: false,
        removeCaracters: false,
        autoPlu: false,
        sizeOfField: false,
        size: 50,
        genPlu: false,
        indexCodBarras: 99999,
        tratarCodBarras: false,
    },
    {
        id: 26,
        des_campo: 'COD_TRIB_ENTRADA',
        visible: false,
        default: 1,
        type: 'number',
        removeCaractersBlock: false,
        removeCaracters: false,
        autoPlu: false,
        sizeOfField: false,
        size: 50,
        genPlu: false,
        indexCodBarras: 99999,
        tratarCodBarras: false,
    },
    {
        id: 27,
        des_campo: 'NUM_CEST',
        visible: false,
        default: 999,
        type: 'string',
        removeCaractersBlock: false,
        removeCaracters: false,
        autoPlu: false,
        sizeOfField: false,
        size: 50,
        genPlu: false,
        indexCodBarras: 99999,
        tratarCodBarras: false,
    },
]
const produto: ColumnsProps[] = [
    {
        id: 1,
        des_campo: 'COD_BARRA_PRINCIPAL',
        visible: false,
        default: 1,
        type: 'string',
        removeCaractersBlock: true,
        removeCaracters: false,
        autoPlu: false,
        sizeOfField: false,
        size: 13,
        genPlu: false,
        indexCodBarras: 99999,
        tratarCodBarras: false,
    },
    {
        id: 2,
        des_campo: 'COD_BARRA_PRINCIPAL_ANT',
        visible: false,
        default: 1,
        type: 'string',
        removeCaractersBlock: true,
        removeCaracters: false,
        autoPlu: false,
        sizeOfField: false,
        size: 13,
        genPlu: false,
        indexCodBarras: 99999,
        tratarCodBarras: false,
    },
    {
        id: 3,
        des_campo: 'COD_BARRA_SPED',
        visible: false,
        default: 1,
        type: 'string',
        removeCaractersBlock: true,
        removeCaracters: false,
        autoPlu: false,
        sizeOfField: false,
        size: 13,
        genPlu: false,
        indexCodBarras: 99999,
        tratarCodBarras: false,
    },
    {
        id: 4,
        des_campo: 'COD_BEM_PRINCIP',
        visible: false,
        default: 1,
        type: 'number',
        removeCaractersBlock: false,
        removeCaracters: false,
        autoPlu: false,
        sizeOfField: false,
        size: 50,
        genPlu: false,
        indexCodBarras: 99999,
        tratarCodBarras: false,
    },
    {
        id: 5,
        des_campo: 'COD_CENTRO_CUSTO',
        visible: false,
        default: 1,
        type: 'number',
        removeCaractersBlock: false,
        removeCaracters: false,
        autoPlu: false,
        sizeOfField: false,
        size: 50,
        genPlu: false,
        indexCodBarras: 99999,
        tratarCodBarras: false,
    },
    {
        id: 6,
        des_campo: 'COD_CLASSIF',
        visible: false,
        default: 1,
        type: 'number',
        removeCaractersBlock: false,
        removeCaracters: false,
        autoPlu: false,
        sizeOfField: false,
        size: 50,
        genPlu: false,
        indexCodBarras: 99999,
        tratarCodBarras: false,
    },
    {
        id: 7,
        des_campo: 'COD_CONSERVACAO',
        visible: false,
        default: 1,
        type: 'number',
        removeCaractersBlock: false,
        removeCaracters: false,
        autoPlu: false,
        sizeOfField: false,
        size: 50,
        genPlu: false,
        indexCodBarras: 99999,
        tratarCodBarras: false,
    },
    {
        id: 8,
        des_campo: 'COD_CRED_PRES',
        visible: false,
        default: 1,
        type: 'number',
        removeCaractersBlock: false,
        removeCaracters: false,
        autoPlu: false,
        sizeOfField: false,
        size: 50,
        genPlu: false,
        indexCodBarras: 99999,
        tratarCodBarras: false,
    },
    {
        id: 9,
        des_campo: 'COD_FORNECEDOR',
        visible: false,
        default: 1,
        type: 'number',
        removeCaractersBlock: false,
        removeCaracters: false,
        autoPlu: false,
        sizeOfField: false,
        size: 50,
        genPlu: false,
        indexCodBarras: 99999,
        tratarCodBarras: false,
    },
    {
        id: 10,
        des_campo: 'COD_GRUPO',
        visible: false,
        default: 1,
        type: 'number',
        removeCaractersBlock: false,
        removeCaracters: false,
        autoPlu: false,
        sizeOfField: false,
        size: 50,
        genPlu: false,
        indexCodBarras: 99999,
        tratarCodBarras: false,
    },
    {
        id: 11,
        des_campo: 'COD_IDENT_GRUPO_BEM',
        visible: false,
        default: 1,
        type: 'number',
        removeCaractersBlock: false,
        removeCaracters: false,
        autoPlu: false,
        sizeOfField: false,
        size: 50,
        genPlu: false,
        indexCodBarras: 99999,
        tratarCodBarras: false,
    },
    {
        id: 12,
        des_campo: 'COD_IDENT_IMOB',
        visible: false,
        default: 1,
        type: 'number',
        removeCaractersBlock: false,
        removeCaracters: false,
        autoPlu: false,
        sizeOfField: false,
        size: 50,
        genPlu: false,
        indexCodBarras: 99999,
        tratarCodBarras: false,
    },
    {
        id: 13,
        des_campo: 'COD_ID_CTB',
        visible: false,
        default: 1,
        type: 'number',
        removeCaractersBlock: false,
        removeCaracters: false,
        autoPlu: false,
        sizeOfField: false,
        size: 50,
        genPlu: false,
        indexCodBarras: 99999,
        tratarCodBarras: false,
    },
    {
        id: 14,
        des_campo: 'COD_ID_CTB_DEPREC',
        visible: false,
        default: 1,
        type: 'number',
        removeCaractersBlock: false,
        removeCaracters: false,
        autoPlu: false,
        sizeOfField: false,
        size: 50,
        genPlu: false,
        indexCodBarras: 99999,
        tratarCodBarras: false,
    },
    {
        id: 15,
        des_campo: 'COD_INFO_NUTRICIONAL',
        visible: false,
        default: 1,
        type: 'number',
        removeCaractersBlock: false,
        removeCaracters: false,
        autoPlu: false,
        sizeOfField: false,
        size: 50,
        genPlu: false,
        indexCodBarras: 99999,
        tratarCodBarras: false,
    },
    {
        id: 16,
        des_campo: 'COD_MARCA',
        visible: false,
        default: 1,
        type: 'number',
        removeCaractersBlock: false,
        removeCaracters: false,
        autoPlu: false,
        sizeOfField: false,
        size: 50,
        genPlu: false,
        indexCodBarras: 99999,
        tratarCodBarras: false,
    },
    {
        id: 17,
        des_campo: 'COD_NAT_BEM',
        visible: false,
        default: 1,
        type: 'number',
        removeCaractersBlock: false,
        removeCaracters: false,
        autoPlu: false,
        sizeOfField: false,
        size: 50,
        genPlu: false,
        indexCodBarras: 99999,
        tratarCodBarras: false,
    },
    {
        id: 18,
        des_campo: 'COD_NBM',
        visible: false,
        default: 1,
        type: 'number',
        removeCaractersBlock: false,
        removeCaracters: false,
        autoPlu: false,
        sizeOfField: false,
        size: 50,
        genPlu: false,
        indexCodBarras: 99999,
        tratarCodBarras: false,
    },
    {
        id: 19,
        des_campo: 'COD_PAI_ECOMM',
        visible: false,
        default: 1,
        type: 'number',
        removeCaractersBlock: false,
        removeCaracters: false,
        autoPlu: false,
        sizeOfField: false,
        size: 50,
        genPlu: false,
        indexCodBarras: 99999,
        tratarCodBarras: false,
    },
    {
        id: 20,
        des_campo: 'COD_PARTNUMBER_ECOMM',
        visible: false,
        default: 1,
        type: 'number',
        removeCaractersBlock: false,
        removeCaracters: false,
        autoPlu: false,
        sizeOfField: false,
        size: 50,
        genPlu: false,
        indexCodBarras: 99999,
        tratarCodBarras: false,
    },
    {
        id: 21,
        des_campo: 'COD_PRODUTO',
        visible: false,
        default: 1,
        type: 'string',
        removeCaractersBlock: false,
        removeCaracters: false,
        autoPlu: false,
        sizeOfField: false,
        size: 50,
        genPlu: false,
        indexCodBarras: 99999,
        tratarCodBarras: false,
    },
    {
        id: 22,
        des_campo: 'COD_PRODUTO_CN',
        visible: false,
        default: 1,
        type: 'string',
        removeCaractersBlock: false,
        removeCaracters: false,
        autoPlu: false,
        sizeOfField: false,
        size: 50,
        genPlu: false,
        indexCodBarras: 99999,
        tratarCodBarras: false,
    },
    {
        id: 23,
        des_campo: 'COD_PRODUTO_CONCORRENTE',
        visible: false,
        default: 1,
        type: 'string',
        removeCaractersBlock: false,
        removeCaracters: false,
        autoPlu: false,
        sizeOfField: false,
        size: 50,
        genPlu: false,
        indexCodBarras: 99999,
        tratarCodBarras: false,
    },
    {
        id: 24,
        des_campo: 'COD_PRODUTO_SIMILAR',
        visible: false,
        default: 1,
        type: 'string',
        removeCaractersBlock: false,
        removeCaracters: false,
        autoPlu: false,
        sizeOfField: false,
        size: 50,
        genPlu: false,
        indexCodBarras: 99999,
        tratarCodBarras: false,
    },
    {
        id: 25,
        des_campo: 'COD_REINF',
        visible: false,
        default: 1,
        type: 'number',
        removeCaractersBlock: false,
        removeCaracters: false,
        autoPlu: false,
        sizeOfField: false,
        size: 50,
        genPlu: false,
        indexCodBarras: 99999,
        tratarCodBarras: false,
    },
    {
        id: 26,
        des_campo: 'COD_SECAO',
        visible: false,
        default: 1,
        type: 'number',
        removeCaractersBlock: false,
        removeCaracters: false,
        autoPlu: false,
        sizeOfField: false,
        size: 50,
        genPlu: false,
        indexCodBarras: 99999,
        tratarCodBarras: false,
    },
    {
        id: 27,
        des_campo: 'COD_SEGMENTO',
        visible: false,
        default: 1,
        type: 'number',
        removeCaractersBlock: false,
        removeCaracters: false,
        autoPlu: false,
        sizeOfField: false,
        size: 50,
        genPlu: false,
        indexCodBarras: 99999,
        tratarCodBarras: false,
    },
    {
        id: 28,
        des_campo: 'COD_SERVICO',
        visible: false,
        default: 1,
        type: 'number',
        removeCaractersBlock: false,
        removeCaracters: false,
        autoPlu: false,
        sizeOfField: false,
        size: 50,
        genPlu: false,
        indexCodBarras: 99999,
        tratarCodBarras: false,
    },
    {
        id: 29,
        des_campo: 'COD_SUB_GRUPO',
        visible: false,
        default: 1,
        type: 'number',
        removeCaractersBlock: false,
        removeCaracters: false,
        autoPlu: false,
        sizeOfField: false,
        size: 50,
        genPlu: false,
        indexCodBarras: 99999,
        tratarCodBarras: false,
    },
    {
        id: 30,
        des_campo: 'COD_TAB_SPED',
        visible: false,
        default: 1,
        type: 'number',
        removeCaractersBlock: false,
        removeCaracters: false,
        autoPlu: false,
        sizeOfField: false,
        size: 50,
        genPlu: false,
        indexCodBarras: 99999,
        tratarCodBarras: false,
    },
    {
        id: 31,
        des_campo: 'CST_PIS_COF_ENTRADA',
        visible: false,
        default: 1,
        type: 'number',
        removeCaractersBlock: false,
        removeCaracters: false,
        autoPlu: false,
        sizeOfField: false,
        size: 50,
        genPlu: false,
        indexCodBarras: 99999,
        tratarCodBarras: false,
    },
    {
        id: 32,
        des_campo: 'CST_PIS_COF_SAIDA',
        visible: false,
        default: 1,
        type: 'number',
        removeCaractersBlock: false,
        removeCaracters: false,
        autoPlu: false,
        sizeOfField: false,
        size: 50,
        genPlu: false,
        indexCodBarras: 99999,
        tratarCodBarras: false,
    },
    {
        id: 33,
        des_campo: 'DES_COD_ANP',
        visible: false,
        default: 1,
        type: 'string',
        removeCaractersBlock: false,
        removeCaracters: false,
        autoPlu: false,
        sizeOfField: false,
        size: 50,
        genPlu: false,
        indexCodBarras: 99999,
        tratarCodBarras: false,
    },
    {
        id: 34,
        des_campo: 'DES_EMBALAGEM',
        visible: false,
        default: 1,
        type: 'string',
        removeCaractersBlock: false,
        removeCaracters: false,
        autoPlu: false,
        sizeOfField: false,
        size: 50,
        genPlu: false,
        indexCodBarras: 99999,
        tratarCodBarras: false,
    },
    {
        id: 35,
        des_campo: 'DES_IMAGEM',
        visible: false,
        default: 1,
        type: 'string',
        removeCaractersBlock: false,
        removeCaracters: false,
        autoPlu: false,
        sizeOfField: false,
        size: 50,
        genPlu: false,
        indexCodBarras: 99999,
        tratarCodBarras: false,
    },
    {
        id: 36,
        des_campo: 'DES_MARCA',
        visible: false,
        default: 1,
        type: 'string',
        removeCaractersBlock: false,
        removeCaracters: false,
        autoPlu: false,
        sizeOfField: false,
        size: 50,
        genPlu: false,
        indexCodBarras: 99999,
        tratarCodBarras: false,
    },
    {
        id: 37,
        des_campo: 'DES_OBSERVACAO',
        visible: false,
        default: 1,
        type: 'string',
        removeCaractersBlock: false,
        removeCaracters: false,
        autoPlu: false,
        sizeOfField: false,
        size: 50,
        genPlu: false,
        indexCodBarras: 99999,
        tratarCodBarras: false,
    },
    {
        id: 38,
        des_campo: 'DES_PLAQUETA',
        visible: false,
        default: 1,
        type: 'string',
        removeCaractersBlock: false,
        removeCaracters: false,
        autoPlu: false,
        sizeOfField: false,
        size: 50,
        genPlu: false,
        indexCodBarras: 99999,
        tratarCodBarras: false,
    },
    {
        id: 39,
        des_campo: 'DES_PRODUTO',
        visible: false,
        default: 1,
        type: 'string',
        removeCaractersBlock: false,
        removeCaracters: false,
        autoPlu: false,
        sizeOfField: false,
        size: 50,
        genPlu: false,
        indexCodBarras: 99999,
        tratarCodBarras: false,
    },
    {
        id: 40,
        des_campo: 'DES_PRODUTO_ANT',
        visible: false,
        default: 1,
        type: 'string',
        removeCaractersBlock: false,
        removeCaracters: false,
        autoPlu: false,
        sizeOfField: false,
        size: 50,
        genPlu: false,
        indexCodBarras: 99999,
        tratarCodBarras: false,
    },
    {
        id: 41,
        des_campo: 'DES_REDUZIDA',
        visible: false,
        default: 1,
        type: 'string',
        removeCaractersBlock: false,
        removeCaracters: false,
        autoPlu: false,
        sizeOfField: false,
        size: 50,
        genPlu: false,
        indexCodBarras: 99999,
        tratarCodBarras: false,
    },
    {
        id: 42,
        des_campo: 'DES_SEGMENTO',
        visible: false,
        default: 1,
        type: 'string',
        removeCaractersBlock: false,
        removeCaracters: false,
        autoPlu: false,
        sizeOfField: false,
        size: 50,
        genPlu: false,
        indexCodBarras: 99999,
        tratarCodBarras: false,
    },
    {
        id: 43,
        des_campo: 'DES_TAB_SPED',
        visible: false,
        default: 1,
        type: 'string',
        removeCaractersBlock: false,
        removeCaracters: false,
        autoPlu: false,
        sizeOfField: false,
        size: 50,
        genPlu: false,
        indexCodBarras: 99999,
        tratarCodBarras: false,
    },
    {
        id: 44,
        des_campo: 'DES_UNIDADE_COMPRA',
        visible: false,
        default: 1,
        type: 'string',
        removeCaractersBlock: false,
        removeCaracters: false,
        autoPlu: false,
        sizeOfField: false,
        size: 50,
        genPlu: false,
        indexCodBarras: 99999,
        tratarCodBarras: false,
    },
    {
        id: 45,
        des_campo: 'DES_UNIDADE_VENDA',
        visible: false,
        default: 1,
        type: 'string',
        removeCaractersBlock: false,
        removeCaracters: false,
        autoPlu: false,
        sizeOfField: false,
        size: 50,
        genPlu: false,
        indexCodBarras: 99999,
        tratarCodBarras: false,
    },
    {
        id: 46,
        des_campo: 'DIAS_VALIDADE',
        visible: false,
        default: 1,
        type: 'number',
        removeCaractersBlock: false,
        removeCaracters: false,
        autoPlu: false,
        sizeOfField: false,
        size: 50,
        genPlu: false,
        indexCodBarras: 99999,
        tratarCodBarras: false,
    },
    {
        id: 47,
        des_campo: 'DTA_ALTERACAO',
        visible: false,
        default: 1,
        type: 'string',
        removeCaractersBlock: false,
        removeCaracters: false,
        autoPlu: false,
        sizeOfField: false,
        size: 50,
        genPlu: false,
        indexCodBarras: 99999,
        tratarCodBarras: false,
    },
    {
        id: 48,
        des_campo: 'DTA_BAIXA',
        visible: false,
        default: 1,
        type: 'string',
        removeCaractersBlock: false,
        removeCaracters: false,
        autoPlu: false,
        sizeOfField: false,
        size: 50,
        genPlu: false,
        indexCodBarras: 99999,
        tratarCodBarras: false,
    },
    {
        id: 49,
        des_campo: 'DTA_CADASTRO',
        visible: false,
        default: 1,
        type: 'string',
        removeCaractersBlock: false,
        removeCaracters: false,
        autoPlu: false,
        sizeOfField: false,
        size: 50,
        genPlu: false,
        indexCodBarras: 99999,
        tratarCodBarras: false,
    },
    {
        id: 50,
        des_campo: 'DTA_DES_PRODUTO_ALT_FIM',
        visible: false,
        default: 1,
        type: 'string',
        removeCaractersBlock: false,
        removeCaracters: false,
        autoPlu: false,
        sizeOfField: false,
        size: 50,
        genPlu: false,
        indexCodBarras: 99999,
        tratarCodBarras: false,
    },
    {
        id: 51,
        des_campo: 'DTA_DES_PRODUTO_ALT_INI',
        visible: false,
        default: 1,
        type: 'string',
        removeCaractersBlock: false,
        removeCaracters: false,
        autoPlu: false,
        sizeOfField: false,
        size: 50,
        genPlu: false,
        indexCodBarras: 99999,
        tratarCodBarras: false,
    },
    {
        id: 52,
        des_campo: 'DTA_ENTRADA',
        visible: false,
        default: 1,
        type: 'string',
        removeCaractersBlock: false,
        removeCaracters: false,
        autoPlu: false,
        sizeOfField: false,
        size: 50,
        genPlu: false,
        indexCodBarras: 99999,
        tratarCodBarras: false,
    },
    {
        id: 53,
        des_campo: 'DTA_ENVIO_SCANNTECH',
        visible: false,
        default: 1,
        type: 'string',
        removeCaractersBlock: false,
        removeCaracters: false,
        autoPlu: false,
        sizeOfField: false,
        size: 50,
        genPlu: false,
        indexCodBarras: 99999,
        tratarCodBarras: false,
    },
    {
        id: 54,
        des_campo: 'DTA_INI_OPER',
        visible: false,
        default: 1,
        type: 'string',
        removeCaractersBlock: false,
        removeCaracters: false,
        autoPlu: false,
        sizeOfField: false,
        size: 50,
        genPlu: false,
        indexCodBarras: 99999,
        tratarCodBarras: false,
    },
    {
        id: 55,
        des_campo: 'FLG_ALCOOLICO',
        visible: false,
        default: 1,
        type: 'boolean',
        removeCaractersBlock: false,
        removeCaracters: false,
        autoPlu: false,
        sizeOfField: false,
        size: 50,
        genPlu: false,
        indexCodBarras: 99999,
        tratarCodBarras: false,
    },
    {
        id: 56,
        des_campo: 'FLG_ATUALIZA_CUSTO_DECOMP',
        visible: false,
        default: 1,
        type: 'boolean',
        removeCaractersBlock: false,
        removeCaracters: false,
        autoPlu: false,
        sizeOfField: false,
        size: 50,
        genPlu: false,
        indexCodBarras: 99999,
        tratarCodBarras: false,
    },
    {
        id: 57,
        des_campo: 'FLG_BEM_FINALIZADO',
        visible: false,
        default: 1,
        type: 'boolean',
        removeCaractersBlock: false,
        removeCaracters: false,
        autoPlu: false,
        sizeOfField: false,
        size: 50,
        genPlu: false,
        indexCodBarras: 99999,
        tratarCodBarras: false,
    },
    {
        id: 58,
        des_campo: 'FLG_CALC_CUSTO_INI_DECOMP',
        visible: false,
        default: 1,
        type: 'boolean',
        removeCaractersBlock: false,
        removeCaracters: false,
        autoPlu: false,
        sizeOfField: false,
        size: 50,
        genPlu: false,
        indexCodBarras: 99999,
        tratarCodBarras: false,
    },
    {
        id: 59,
        des_campo: 'FLG_DEPRECIADO',
        visible: false,
        default: 1,
        type: 'boolean',
        removeCaractersBlock: false,
        removeCaracters: false,
        autoPlu: false,
        sizeOfField: false,
        size: 50,
        genPlu: false,
        indexCodBarras: 99999,
        tratarCodBarras: false,
    },
    {
        id: 60,
        des_campo: 'FLG_ENVIA_BALANCA',
        visible: false,
        default: 1,
        type: 'boolean',
        removeCaractersBlock: false,
        removeCaracters: false,
        autoPlu: false,
        sizeOfField: false,
        size: 50,
        genPlu: false,
        indexCodBarras: 99999,
        tratarCodBarras: false,
    },
    {
        id: 61,
        des_campo: 'FLG_ICMS_ANTECIPADO',
        visible: false,
        default: 1,
        type: 'boolean',
        removeCaractersBlock: false,
        removeCaracters: false,
        autoPlu: false,
        sizeOfField: false,
        size: 50,
        genPlu: false,
        indexCodBarras: 99999,
        tratarCodBarras: false,
    },
    {
        id: 62,
        des_campo: 'FLG_IMPORTA',
        visible: false,
        default: 1,
        type: 'boolean',
        removeCaractersBlock: false,
        removeCaracters: false,
        autoPlu: false,
        sizeOfField: false,
        size: 50,
        genPlu: false,
        indexCodBarras: 99999,
        tratarCodBarras: false,
    },
    {
        id: 63,
        des_campo: 'FLG_LEASING',
        visible: false,
        default: 1,
        type: 'boolean',
        removeCaractersBlock: false,
        removeCaracters: false,
        autoPlu: false,
        sizeOfField: false,
        size: 50,
        genPlu: false,
        indexCodBarras: 99999,
        tratarCodBarras: false,
    },
    {
        id: 64,
        des_campo: 'FLG_NAO_ICMS',
        visible: false,
        default: 1,
        type: 'boolean',
        removeCaractersBlock: false,
        removeCaracters: false,
        autoPlu: false,
        sizeOfField: false,
        size: 50,
        genPlu: false,
        indexCodBarras: 99999,
        tratarCodBarras: false,
    },
    {
        id: 65,
        des_campo: 'FLG_NAO_PIS_COFINS',
        visible: false,
        default: 1,
        type: 'boolean',
        removeCaractersBlock: false,
        removeCaracters: false,
        autoPlu: false,
        sizeOfField: false,
        size: 50,
        genPlu: false,
        indexCodBarras: 99999,
        tratarCodBarras: false,
    },
    {
        id: 66,
        des_campo: 'FLG_NAO_PIS_COFINS_MONO',
        visible: false,
        default: 1,
        type: 'boolean',
        removeCaractersBlock: false,
        removeCaracters: false,
        autoPlu: false,
        sizeOfField: false,
        size: 50,
        genPlu: false,
        indexCodBarras: 99999,
        tratarCodBarras: false,
    },
    {
        id: 67,
        des_campo: 'FLG_NAO_PIS_COFINS_ST',
        visible: false,
        default: 1,
        type: 'boolean',
        removeCaractersBlock: false,
        removeCaracters: false,
        autoPlu: false,
        sizeOfField: false,
        size: 50,
        genPlu: false,
        indexCodBarras: 99999,
        tratarCodBarras: false,
    },
    {
        id: 68,
        des_campo: 'FLG_PERMITE_PARC',
        visible: false,
        default: 1,
        type: 'boolean',
        removeCaractersBlock: false,
        removeCaracters: false,
        autoPlu: false,
        sizeOfField: false,
        size: 50,
        genPlu: false,
        indexCodBarras: 99999,
        tratarCodBarras: false,
    },
    {
        id: 69,
        des_campo: 'FLG_PROD_IMPORTADO',
        visible: false,
        default: 1,
        type: 'boolean',
        removeCaractersBlock: false,
        removeCaracters: false,
        autoPlu: false,
        sizeOfField: false,
        size: 50,
        genPlu: false,
        indexCodBarras: 99999,
        tratarCodBarras: false,
    },
    {
        id: 70,
        des_campo: 'FLG_PROD_SINC_REP',
        visible: false,
        default: 1,
        type: 'boolean',
        removeCaractersBlock: false,
        removeCaracters: false,
        autoPlu: false,
        sizeOfField: false,
        size: 50,
        genPlu: false,
        indexCodBarras: 99999,
        tratarCodBarras: false,
    },
    {
        id: 71,
        des_campo: 'FLG_RASTREAVEL',
        visible: false,
        default: 1,
        type: 'boolean',
        removeCaractersBlock: false,
        removeCaracters: false,
        autoPlu: false,
        sizeOfField: false,
        size: 50,
        genPlu: false,
        indexCodBarras: 99999,
        tratarCodBarras: false,
    },
    {
        id: 72,
        des_campo: 'FLG_SEM_COD_BARRA',
        visible: false,
        default: 1,
        type: 'boolean',
        removeCaractersBlock: false,
        removeCaracters: false,
        autoPlu: false,
        sizeOfField: false,
        size: 50,
        genPlu: false,
        indexCodBarras: 99999,
        tratarCodBarras: false,
    },
    {
        id: 73,
        des_campo: 'IMAGEM_PRODUTO',
        visible: false,
        default: 1,
        type: 'string',
        removeCaractersBlock: false,
        removeCaracters: false,
        autoPlu: false,
        sizeOfField: false,
        size: 50,
        genPlu: false,
        indexCodBarras: 99999,
        tratarCodBarras: false,
    },
    {
        id: 74,
        des_campo: 'IPV',
        visible: false,
        default: 1,
        type: 'boolean',
        removeCaractersBlock: false,
        removeCaracters: false,
        autoPlu: false,
        sizeOfField: false,
        size: 50,
        genPlu: false,
        indexCodBarras: 99999,
        tratarCodBarras: false,
    },
    {
        id: 75,
        des_campo: 'MES_ANO_INI_DEPREC',
        visible: false,
        default: 1,
        type: 'string',
        removeCaractersBlock: false,
        removeCaracters: false,
        autoPlu: false,
        sizeOfField: false,
        size: 50,
        genPlu: false,
        indexCodBarras: 99999,
        tratarCodBarras: false,
    },
    {
        id: 76,
        des_campo: 'NUM_ALTURA',
        visible: false,
        default: 1,
        type: 'number',
        removeCaractersBlock: false,
        removeCaracters: false,
        autoPlu: false,
        sizeOfField: false,
        size: 50,
        genPlu: false,
        indexCodBarras: 99999,
        tratarCodBarras: false,
    },
    {
        id: 77,
        des_campo: 'NUM_LARGURA',
        visible: false,
        default: 1,
        type: 'number',
        removeCaractersBlock: false,
        removeCaracters: false,
        autoPlu: false,
        sizeOfField: false,
        size: 50,
        genPlu: false,
        indexCodBarras: 99999,
        tratarCodBarras: false,
    },
    {
        id: 78,
        des_campo: 'NUM_LOTE',
        visible: false,
        default: 1,
        type: 'number',
        removeCaractersBlock: false,
        removeCaracters: false,
        autoPlu: false,
        sizeOfField: false,
        size: 50,
        genPlu: false,
        indexCodBarras: 99999,
        tratarCodBarras: false,
    },
    {
        id: 79,
        des_campo: 'NUM_NF',
        visible: false,
        default: 1,
        type: 'number',
        removeCaractersBlock: false,
        removeCaracters: false,
        autoPlu: false,
        sizeOfField: false,
        size: 50,
        genPlu: false,
        indexCodBarras: 99999,
        tratarCodBarras: false,
    },
    {
        id: 80,
        des_campo: 'NUM_PROFUNDIDADE',
        visible: false,
        default: 1,
        type: 'number',
        removeCaractersBlock: false,
        removeCaracters: false,
        autoPlu: false,
        sizeOfField: false,
        size: 50,
        genPlu: false,
        indexCodBarras: 99999,
        tratarCodBarras: false,
    },
    {
        id: 81,
        des_campo: 'NUM_SIF',
        visible: false,
        default: 1,
        type: 'number',
        removeCaractersBlock: false,
        removeCaracters: false,
        autoPlu: false,
        sizeOfField: false,
        size: 50,
        genPlu: false,
        indexCodBarras: 99999,
        tratarCodBarras: false,
    },
    {
        id: 82,
        des_campo: 'NUM_SIM',
        visible: false,
        default: 1,
        type: 'number',
        removeCaractersBlock: false,
        removeCaracters: false,
        autoPlu: false,
        sizeOfField: false,
        size: 50,
        genPlu: false,
        indexCodBarras: 99999,
        tratarCodBarras: false,
    },
    {
        id: 83,
        des_campo: 'NUM_VIDA_UTIL',
        visible: false,
        default: 1,
        type: 'number',
        removeCaractersBlock: false,
        removeCaracters: false,
        autoPlu: false,
        sizeOfField: false,
        size: 50,
        genPlu: false,
        indexCodBarras: 99999,
        tratarCodBarras: false,
    },
    {
        id: 84,
        des_campo: 'PERECIVEL',
        visible: false,
        default: 1,
        type: 'boolean',
        removeCaractersBlock: false,
        removeCaracters: false,
        autoPlu: false,
        sizeOfField: false,
        size: 50,
        genPlu: false,
        indexCodBarras: 99999,
        tratarCodBarras: false,
    },
    {
        id: 85,
        des_campo: 'PER_ACRESC_ASSOC',
        visible: false,
        default: 1,
        type: 'number',
        removeCaractersBlock: false,
        removeCaracters: false,
        autoPlu: false,
        sizeOfField: false,
        size: 50,
        genPlu: false,
        indexCodBarras: 99999,
        tratarCodBarras: false,
    },
    {
        id: 86,
        des_campo: 'PER_DEPREC_ACUM',
        visible: false,
        default: 1,
        type: 'number',
        removeCaractersBlock: false,
        removeCaracters: false,
        autoPlu: false,
        sizeOfField: false,
        size: 50,
        genPlu: false,
        indexCodBarras: 99999,
        tratarCodBarras: false,
    },
    {
        id: 87,
        des_campo: 'PER_DESP_ASSOC',
        visible: false,
        default: 1,
        type: 'number',
        removeCaractersBlock: false,
        removeCaracters: false,
        autoPlu: false,
        sizeOfField: false,
        size: 50,
        genPlu: false,
        indexCodBarras: 99999,
        tratarCodBarras: false,
    },
    {
        id: 88,
        des_campo: 'PER_GLP',
        visible: false,
        default: 1,
        type: 'number',
        removeCaractersBlock: false,
        removeCaracters: false,
        autoPlu: false,
        sizeOfField: false,
        size: 50,
        genPlu: false,
        indexCodBarras: 99999,
        tratarCodBarras: false,
    },
    {
        id: 89,
        des_campo: 'PER_GNI',
        visible: false,
        default: 1,
        type: 'number',
        removeCaractersBlock: false,
        removeCaracters: false,
        autoPlu: false,
        sizeOfField: false,
        size: 50,
        genPlu: false,
        indexCodBarras: 99999,
        tratarCodBarras: false,
    },
    {
        id: 90,
        des_campo: 'PER_GNN',
        visible: false,
        default: 1,
        type: 'number',
        removeCaractersBlock: false,
        removeCaracters: false,
        autoPlu: false,
        sizeOfField: false,
        size: 50,
        genPlu: false,
        indexCodBarras: 99999,
        tratarCodBarras: false,
    },
    {
        id: 91,
        des_campo: 'PER_PERDA',
        visible: false,
        default: 1,
        type: 'number',
        removeCaractersBlock: false,
        removeCaracters: false,
        autoPlu: false,
        sizeOfField: false,
        size: 50,
        genPlu: false,
        indexCodBarras: 99999,
        tratarCodBarras: false,
    },
    {
        id: 92,
        des_campo: 'PER_TAXA_DEPREC',
        visible: false,
        default: 1,
        type: 'number',
        removeCaractersBlock: false,
        removeCaracters: false,
        autoPlu: false,
        sizeOfField: false,
        size: 50,
        genPlu: false,
        indexCodBarras: 99999,
        tratarCodBarras: false,
    },
    {
        id: 93,
        des_campo: 'PER_TOLERA_2F',
        visible: false,
        default: 1,
        type: 'number',
        removeCaractersBlock: false,
        removeCaracters: false,
        autoPlu: false,
        sizeOfField: false,
        size: 50,
        genPlu: false,
        indexCodBarras: 99999,
        tratarCodBarras: false,
    },
    {
        id: 94,
        des_campo: 'PER_TOLERA_IPV',
        visible: false,
        default: 1,
        type: 'number',
        removeCaractersBlock: false,
        removeCaracters: false,
        autoPlu: false,
        sizeOfField: false,
        size: 50,
        genPlu: false,
        indexCodBarras: 99999,
        tratarCodBarras: false,
    },
    {
        id: 95,
        des_campo: 'QTD_DIVISOR_PRECO',
        visible: false,
        default: 1,
        type: 'number',
        removeCaractersBlock: false,
        removeCaracters: false,
        autoPlu: false,
        sizeOfField: false,
        size: 50,
        genPlu: false,
        indexCodBarras: 99999,
        tratarCodBarras: false,
    },
    {
        id: 96,
        des_campo: 'QTD_EMBALAGEM_COMPRA',
        visible: false,
        default: 1,
        type: 'number',
        removeCaractersBlock: false,
        removeCaracters: false,
        autoPlu: false,
        sizeOfField: false,
        size: 50,
        genPlu: false,
        indexCodBarras: 99999,
        tratarCodBarras: false,
    },
    {
        id: 97,
        des_campo: 'QTD_EMBALAGEM_VENDA',
        visible: false,
        default: 1,
        type: 'number',
        removeCaractersBlock: false,
        removeCaracters: false,
        autoPlu: false,
        sizeOfField: false,
        size: 50,
        genPlu: false,
        indexCodBarras: 99999,
        tratarCodBarras: false,
    },
    {
        id: 98,
        des_campo: 'QTD_LIMITE_GONDOLA',
        visible: false,
        default: 1,
        type: 'number',
        removeCaractersBlock: false,
        removeCaracters: false,
        autoPlu: false,
        sizeOfField: false,
        size: 50,
        genPlu: false,
        indexCodBarras: 99999,
        tratarCodBarras: false,
    },
    {
        id: 99,
        des_campo: 'QTD_MESES_ICMS_RECUP',
        visible: false,
        default: 1,
        type: 'number',
        removeCaractersBlock: false,
        removeCaracters: false,
        autoPlu: false,
        sizeOfField: false,
        size: 50,
        genPlu: false,
        indexCodBarras: 99999,
        tratarCodBarras: false,
    },
    {
        id: 100,
        des_campo: 'QTD_MESES_PIS_COF_RECUP',
        visible: false,
        default: 1,
        type: 'number',
        removeCaractersBlock: false,
        removeCaracters: false,
        autoPlu: false,
        sizeOfField: false,
        size: 50,
        genPlu: false,
        indexCodBarras: 99999,
        tratarCodBarras: false,
    },
    {
        id: 101,
        des_campo: 'QTD_MES_NOVO_COMP',
        visible: false,
        default: 1,
        type: 'number',
        removeCaractersBlock: false,
        removeCaracters: false,
        autoPlu: false,
        sizeOfField: false,
        size: 50,
        genPlu: false,
        indexCodBarras: 99999,
        tratarCodBarras: false,
    },
    {
        id: 102,
        des_campo: 'STATUS',
        visible: false,
        default: 1,
        type: 'number',
        removeCaractersBlock: false,
        removeCaracters: false,
        autoPlu: false,
        sizeOfField: false,
        size: 50,
        genPlu: false,
        indexCodBarras: 99999,
        tratarCodBarras: false,
    },
    {
        id: 103,
        des_campo: 'TIPO_BEM',
        visible: false,
        default: 1,
        type: 'number',
        removeCaractersBlock: false,
        removeCaracters: false,
        autoPlu: false,
        sizeOfField: false,
        size: 50,
        genPlu: false,
        indexCodBarras: 99999,
        tratarCodBarras: false,
    },
    {
        id: 104,
        des_campo: 'TIPO_CRED_PIS_COF_IMOB',
        visible: false,
        default: 1,
        type: 'number',
        removeCaractersBlock: false,
        removeCaracters: false,
        autoPlu: false,
        sizeOfField: false,
        size: 50,
        genPlu: false,
        indexCodBarras: 99999,
        tratarCodBarras: false,
    },
    {
        id: 105,
        des_campo: 'TIPO_ESPECIE',
        visible: false,
        default: 1,
        type: 'number',
        removeCaractersBlock: false,
        removeCaracters: false,
        autoPlu: false,
        sizeOfField: false,
        size: 50,
        genPlu: false,
        indexCodBarras: 99999,
        tratarCodBarras: false,
    },
    {
        id: 106,
        des_campo: 'TIPO_EVENTO',
        visible: false,
        default: 1,
        type: 'number',
        removeCaractersBlock: false,
        removeCaracters: false,
        autoPlu: false,
        sizeOfField: false,
        size: 50,
        genPlu: false,
        indexCodBarras: 99999,
        tratarCodBarras: false,
    },
    {
        id: 107,
        des_campo: 'TIPO_EXPLOSAO_COMPRA',
        visible: false,
        default: 1,
        type: 'number',
        removeCaractersBlock: false,
        removeCaracters: false,
        autoPlu: false,
        sizeOfField: false,
        size: 50,
        genPlu: false,
        indexCodBarras: 99999,
        tratarCodBarras: false,
    },
    {
        id: 108,
        des_campo: 'TIPO_FORMA_EXPLOSAO',
        visible: false,
        default: 1,
        type: 'number',
        removeCaractersBlock: false,
        removeCaracters: false,
        autoPlu: false,
        sizeOfField: false,
        size: 50,
        genPlu: false,
        indexCodBarras: 99999,
        tratarCodBarras: false,
    },
    {
        id: 109,
        des_campo: 'TIPO_IPI',
        visible: false,
        default: 1,
        type: 'number',
        removeCaractersBlock: false,
        removeCaracters: false,
        autoPlu: false,
        sizeOfField: false,
        size: 50,
        genPlu: false,
        indexCodBarras: 99999,
        tratarCodBarras: false,
    },
    {
        id: 110,
        des_campo: 'TIPO_ITEM',
        visible: false,
        default: 1,
        type: 'number',
        removeCaractersBlock: false,
        removeCaracters: false,
        autoPlu: false,
        sizeOfField: false,
        size: 50,
        genPlu: false,
        indexCodBarras: 99999,
        tratarCodBarras: false,
    },
    {
        id: 111,
        des_campo: 'TIPO_MULTIPLICACAO',
        visible: false,
        default: 1,
        type: 'number',
        removeCaractersBlock: false,
        removeCaracters: false,
        autoPlu: false,
        sizeOfField: false,
        size: 50,
        genPlu: false,
        indexCodBarras: 99999,
        tratarCodBarras: false,
    },
    {
        id: 112,
        des_campo: 'TIPO_NAO_PIS_COFINS',
        visible: false,
        default: 1,
        type: 'number',
        removeCaractersBlock: false,
        removeCaracters: false,
        autoPlu: false,
        sizeOfField: false,
        size: 50,
        genPlu: false,
        indexCodBarras: 99999,
        tratarCodBarras: false,
    },
    {
        id: 113,
        des_campo: 'TIPO_PRODUTO',
        visible: false,
        default: 1,
        type: 'number',
        removeCaractersBlock: false,
        removeCaracters: false,
        autoPlu: false,
        sizeOfField: false,
        size: 50,
        genPlu: false,
        indexCodBarras: 99999,
        tratarCodBarras: false,
    },
    {
        id: 114,
        des_campo: 'TIPO_REGRA_VENDA_PDV',
        visible: false,
        default: 1,
        type: 'number',
        removeCaractersBlock: false,
        removeCaracters: false,
        autoPlu: false,
        sizeOfField: false,
        size: 50,
        genPlu: false,
        indexCodBarras: 99999,
        tratarCodBarras: false,
    },
    {
        id: 115,
        des_campo: 'TIPO_SOBREPOSTO',
        visible: false,
        default: 1,
        type: 'number',
        removeCaractersBlock: false,
        removeCaracters: false,
        autoPlu: false,
        sizeOfField: false,
        size: 50,
        genPlu: false,
        indexCodBarras: 99999,
        tratarCodBarras: false,
    },
    {
        id: 116,
        des_campo: 'TIPO_STATUS_MXF',
        visible: false,
        default: 1,
        type: 'number',
        removeCaractersBlock: false,
        removeCaracters: false,
        autoPlu: false,
        sizeOfField: false,
        size: 50,
        genPlu: false,
        indexCodBarras: 99999,
        tratarCodBarras: false,
    },
    {
        id: 117,
        des_campo: 'USUARIO',
        visible: false,
        default: 1,
        type: 'number',
        removeCaractersBlock: false,
        removeCaracters: false,
        autoPlu: false,
        sizeOfField: false,
        size: 50,
        genPlu: false,
        indexCodBarras: 99999,
        tratarCodBarras: false,
    },
    {
        id: 118,
        des_campo: 'VAL_ACUM',
        visible: false,
        default: 1,
        type: 'number',
        removeCaractersBlock: false,
        removeCaracters: false,
        autoPlu: false,
        sizeOfField: false,
        size: 50,
        genPlu: false,
        indexCodBarras: 99999,
        tratarCodBarras: false,
    },
    {
        id: 119,
        des_campo: 'VAL_AQUISICAO',
        visible: false,
        default: 1,
        type: 'number',
        removeCaractersBlock: false,
        removeCaracters: false,
        autoPlu: false,
        sizeOfField: false,
        size: 50,
        genPlu: false,
        indexCodBarras: 99999,
        tratarCodBarras: false,
    },
    {
        id: 120,
        des_campo: 'VAL_BAIXADO',
        visible: false,
        default: 1,
        type: 'number',
        removeCaractersBlock: false,
        removeCaracters: false,
        autoPlu: false,
        sizeOfField: false,
        size: 50,
        genPlu: false,
        indexCodBarras: 99999,
        tratarCodBarras: false,
    },
    {
        id: 121,
        des_campo: 'VAL_BONUS',
        visible: false,
        default: 1,
        type: 'number',
        removeCaractersBlock: false,
        removeCaracters: false,
        autoPlu: false,
        sizeOfField: false,
        size: 50,
        genPlu: false,
        indexCodBarras: 99999,
        tratarCodBarras: false,
    },
    {
        id: 122,
        des_campo: 'VAL_GRAMATURA',
        visible: false,
        default: 1,
        type: 'number',
        removeCaractersBlock: false,
        removeCaracters: false,
        autoPlu: false,
        sizeOfField: false,
        size: 50,
        genPlu: false,
        indexCodBarras: 99999,
        tratarCodBarras: false,
    },
    {
        id: 123,
        des_campo: 'VAL_ICMS_RECUP',
        visible: false,
        default: 1,
        type: 'number',
        removeCaractersBlock: false,
        removeCaracters: false,
        autoPlu: false,
        sizeOfField: false,
        size: 50,
        genPlu: false,
        indexCodBarras: 99999,
        tratarCodBarras: false,
    },
    {
        id: 124,
        des_campo: 'VAL_IPI',
        visible: false,
        default: 1,
        type: 'number',
        removeCaractersBlock: false,
        removeCaracters: false,
        autoPlu: false,
        sizeOfField: false,
        size: 50,
        genPlu: false,
        indexCodBarras: 99999,
        tratarCodBarras: false,
    },
    {
        id: 125,
        des_campo: 'VAL_ORIG_BEM',
        visible: false,
        default: 1,
        type: 'number',
        removeCaractersBlock: false,
        removeCaracters: false,
        autoPlu: false,
        sizeOfField: false,
        size: 50,
        genPlu: false,
        indexCodBarras: 99999,
        tratarCodBarras: false,
    },
    {
        id: 126,
        des_campo: 'VAL_PART_GLP',
        visible: false,
        default: 1,
        type: 'number',
        removeCaractersBlock: false,
        removeCaracters: false,
        autoPlu: false,
        sizeOfField: false,
        size: 50,
        genPlu: false,
        indexCodBarras: 99999,
        tratarCodBarras: false,
    },
    {
        id: 127,
        des_campo: 'VAL_PESO',
        visible: false,
        default: 1,
        type: 'number',
        removeCaractersBlock: false,
        removeCaracters: false,
        autoPlu: false,
        sizeOfField: false,
        size: 50,
        genPlu: false,
        indexCodBarras: 99999,
        tratarCodBarras: false,
    },
    {
        id: 128,
        des_campo: 'VAL_PESO_EMB',
        visible: false,
        default: 1,
        type: 'number',
        removeCaractersBlock: false,
        removeCaracters: false,
        autoPlu: false,
        sizeOfField: false,
        size: 50,
        genPlu: false,
        indexCodBarras: 99999,
        tratarCodBarras: false,
    },
    {
        id: 129,
        des_campo: 'VAL_PIS_COF_RECUP',
        visible: false,
        default: 1,
        type: 'number',
        removeCaractersBlock: false,
        removeCaracters: false,
        autoPlu: false,
        sizeOfField: false,
        size: 50,
        genPlu: false,
        indexCodBarras: 99999,
        tratarCodBarras: false,
    },
    {
        id: 130,
        des_campo: 'VAL_RESIDUAL',
        visible: false,
        default: 1,
        type: 'number',
        removeCaractersBlock: false,
        removeCaracters: false,
        autoPlu: false,
        sizeOfField: false,
        size: 50,
        genPlu: false,
        indexCodBarras: 99999,
        tratarCodBarras: false,
    },
    {
        id: 131,
        des_campo: 'VAL_VDA_PESO_BRUTO',
        visible: false,
        default: 1,
        type: 'number',
        removeCaractersBlock: false,
        removeCaracters: false,
        autoPlu: false,
        sizeOfField: false,
        size: 50,
        genPlu: false,
        indexCodBarras: 99999,
        tratarCodBarras: false,
    },
]

export { ncm, produto }